### ISSUE TITLE
Quick question...

### ISSUE THREAD

**Issue by glennguy** [matthuisman/decryptmodules#1]
Hi Matt, 

I can't send pms on the Kodi forum, so....

Have you had any success getting widevine going on Kodi 17 for Android? I could swear that it worked before but recently just garbled picture and no sound - seems to not actually decrypt correctly. Have tried contacting peak3d but it seems he's on extended holidays.

btw, you can email me at glennguy83 at the popular g site.

**Comment by matthuisman** [comment]
It never worked as far as I'm aware.

I asked Peak3d about it, and he said there were changes in the actual KODI source code required for Android to work and these changes are only in 18.
So, even using a latest inpustream.adaptive won't work.

https://forum.kodi.tv/showthread.php?tid=303609&pid=2561548#pid2561548

That's what I gathered from it anyway. I may be wrong.
